# **Kaggle Challenge 3: Đề tài dự đoán thể loại nhạc.**
# **PHẦN 3: TIỀN XỬ LÝ DỮ LIỆU**

## 1. Mô tả vấn đề
+ **Mô tả**:
   - Dự báo thể loại nhạc dựa trên 17 tính chất của dataset.
   - Dữ liệu đầu vào gồm 2 file:
      * train_clean.pkl: Dữ liệu từ file train đã được xử lý ở phần 1.
      * test_clean.pkl: Dữ liệu từ file test đã được xử lý ở phần 1.

+ **Mục tiêu**:
   - Xử lý dữ liệu để các mô hình máy học có thể học hiệu quả, thêm một số đặc trưng giúp cải tiến hiệu suất mô hình.

## 2. Chuẩn bị vấn đề

### 2.1. Import các thư viện cần thiết

In [28]:
# Load libraries
from IPython import display
import numpy as np
import pickle

import matplotlib.pyplot as plt
import random

import pandas as pd
import seaborn as sns

from sklearn.preprocessing import OneHotEncoder, StandardScaler, MinMaxScaler, RobustScaler

# Hiển thị tối đa 200 cột
pd.set_option('display.max_columns', 200)

### 2.2. Đọc dataset train và test từ dataset đã xử lý trong phần dọn dẹp dữ liệu
Đọc các file .pkl trong thư mục /clean/data

In [29]:
train_data = pd.DataFrame(pd.read_pickle("../clean/data/train_clean.pkl"))
test_data = pd.DataFrame(pd.read_pickle("../clean/data/test_clean.pkl"))

### 2.3. Kiểm tra dữ liệu dataset train và test

In [30]:
train_data.head()

,Artist Name,Track Name,Popularity,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,duration_in min/ms,time_signature,Class
0,Marina Maximilian,Not Afraid,37.0,0.334,0.536,9.0,-6.649,0,0.0381,0.378000,0.003475,0.106,0.235,152.429,204947.0,4,9
1,The Black Keys,Howlin' for You,67.0,0.725,0.747,11.0,-5.545,1,0.0876,0.027200,0.046800,0.104,0.380,132.921,191956.0,4,6
2,Royal & the Serpent,phuck u,44.0,0.584,0.804,7.0,-6.094,1,0.0619,0.000968,0.635000,0.284,0.635,159.953,161037.0,4,10
3,Detroit Blues Band,Missing You,12.0,0.515,0.308,5.0,-14.711,1,0.0312,0.907000,0.021300,0.300,0.501,172.472,298093.0,3,2
4,Coast Contra,My Lady,48.0,0.565,0.777,6.0,-5.096,0,0.2490,0.183000,0.003475,0.211,0.619,88.311,254145.0,4,5

In [31]:
test_data.head()

,Artist Name,Track Name,Popularity,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,duration_in min/ms,time_signature
0,Juan Pablo Vega,Matando (feat. Vic Mirallas),44.0,0.691,0.670,2.0,-7.093,0,0.0941,0.075700,0.035200,0.1970,0.635,89.965,200000.0,4
1,Kappi Kat,Baarish,14.0,0.461,0.777,2.0,-7.469,1,0.0306,0.388000,0.923000,0.2910,0.525,163.043,283909.0,4
2,Plain White T's,Hey There Delilah,80.0,0.656,0.291,2.0,-10.572,1,0.0293,0.872000,0.002445,0.1140,0.298,103.971,232533.0,4
3,WALK THE MOON,Different Colors,52.0,0.480,0.826,6.0,-4.602,1,0.0397,0.000797,0.000001,0.1250,0.687,96.000,222053.0,4
4,Peled,◊ß◊®◊ô◊ñ,23.0,0.734,0.729,1.0,-6.381,0,0.2830,0.147000,0.004930,0.0672,0.805,76.030,118439.0,4

## 3. Tiền xử lý dữ liệu

In [32]:
train_y = train_data["Class"]  # tách biến mục tiêu ra khỏi tập train
train_y.to_pickle("./data/train_y_unprocessed.pkl") # Lưu file chưa xử lý để phục hồi lại giá trị ban đầu sau khi train.
train_data = train_data.drop(columns="Class")

### 3.1. Xử lý các biến số có phân bố liên tục
Các biến có phân bố liên tục bao gồm: Popularity, energy, loudness, speechiness, acousticness, instrumentalness, liveness, valence, tempo, duration_in min/ms

#### **1) Biến Popularity**
Biến này có phân bố tương đối ổn định, có thể chuẩn hóa bằng StandardScaler.

In [33]:
# Chuẩn hóa bằng StandardScaler
scaler = StandardScaler()

train_data[["Popularity"]] = scaler.fit_transform(train_data[["Popularity"]])
test_data[["Popularity"]] = scaler.transform(test_data[["Popularity"]])

#### **2) Biến Energy**
Biến này có phân bố ổn định nhưng lệch trái

#### **3) Biến Loudness**
Biến này có phân bố ổn định nhưng lệch trái

In [ ]:
train_data["loudness"] = train_data["loudness"].apply(np.log1p)
test_data["loudness"] = test_data["loudness"].apply(np.log1p)

d:\Installs\Anaconda\Lib\site-packages\pandas\core\arraylike.py:399: RuntimeWarning: invalid value encountered in log1p
  result = getattr(ufunc, method)(*inputs, **kwargs)